# Generated by Django 4.2.7 on 2023-11-21 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='photo',
            field=models.ImageField(blank=True, default=None, upload_to='media/%Y-%m-%d/', verbose_name='Фото'),
        ),
    ]
